//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseManagementClient.PaymentServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentModel", Namespace="http://schemas.datacontract.org/2004/07/ExpenseManagement.Models")]
    [System.SerializableAttribute()]
    public partial class PaymentModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float PaymentAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PaymentDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentFromUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PaymentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentToUserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float PaymentAmount {
            get {
                return this.PaymentAmountField;
            }
            set {
                if ((this.PaymentAmountField.Equals(value) != true)) {
                    this.PaymentAmountField = value;
                    this.RaisePropertyChanged("PaymentAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PaymentDate {
            get {
                return this.PaymentDateField;
            }
            set {
                if ((this.PaymentDateField.Equals(value) != true)) {
                    this.PaymentDateField = value;
                    this.RaisePropertyChanged("PaymentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentDescription {
            get {
                return this.PaymentDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentDescriptionField, value) != true)) {
                    this.PaymentDescriptionField = value;
                    this.RaisePropertyChanged("PaymentDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentFromUser {
            get {
                return this.PaymentFromUserField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentFromUserField, value) != true)) {
                    this.PaymentFromUserField = value;
                    this.RaisePropertyChanged("PaymentFromUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PaymentId {
            get {
                return this.PaymentIdField;
            }
            set {
                if ((this.PaymentIdField.Equals(value) != true)) {
                    this.PaymentIdField = value;
                    this.RaisePropertyChanged("PaymentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentToUser {
            get {
                return this.PaymentToUserField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentToUserField, value) != true)) {
                    this.PaymentToUserField = value;
                    this.RaisePropertyChanged("PaymentToUser");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PaymentServiceReference.IPaymentService")]
    public interface IPaymentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/AddPayment", ReplyAction="http://tempuri.org/IPaymentService/AddPaymentResponse")]
        ExpenseManagementClient.PaymentServiceReference.PaymentModel AddPayment(ExpenseManagementClient.PaymentServiceReference.PaymentModel payment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/AddPayment", ReplyAction="http://tempuri.org/IPaymentService/AddPaymentResponse")]
        System.Threading.Tasks.Task<ExpenseManagementClient.PaymentServiceReference.PaymentModel> AddPaymentAsync(ExpenseManagementClient.PaymentServiceReference.PaymentModel payment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/DeletePayment", ReplyAction="http://tempuri.org/IPaymentService/DeletePaymentResponse")]
        bool DeletePayment(int paymentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/DeletePayment", ReplyAction="http://tempuri.org/IPaymentService/DeletePaymentResponse")]
        System.Threading.Tasks.Task<bool> DeletePaymentAsync(int paymentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/UpdatePayment", ReplyAction="http://tempuri.org/IPaymentService/UpdatePaymentResponse")]
        ExpenseManagementClient.PaymentServiceReference.PaymentModel UpdatePayment(ExpenseManagementClient.PaymentServiceReference.PaymentModel payment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/UpdatePayment", ReplyAction="http://tempuri.org/IPaymentService/UpdatePaymentResponse")]
        System.Threading.Tasks.Task<ExpenseManagementClient.PaymentServiceReference.PaymentModel> UpdatePaymentAsync(ExpenseManagementClient.PaymentServiceReference.PaymentModel payment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/ViewSinglePayment", ReplyAction="http://tempuri.org/IPaymentService/ViewSinglePaymentResponse")]
        ExpenseManagementClient.PaymentServiceReference.PaymentModel ViewSinglePayment(int paymentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/ViewSinglePayment", ReplyAction="http://tempuri.org/IPaymentService/ViewSinglePaymentResponse")]
        System.Threading.Tasks.Task<ExpenseManagementClient.PaymentServiceReference.PaymentModel> ViewSinglePaymentAsync(int paymentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/ViewAllPayment", ReplyAction="http://tempuri.org/IPaymentService/ViewAllPaymentResponse")]
        ExpenseManagementClient.PaymentServiceReference.PaymentModel[] ViewAllPayment();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/ViewAllPayment", ReplyAction="http://tempuri.org/IPaymentService/ViewAllPaymentResponse")]
        System.Threading.Tasks.Task<ExpenseManagementClient.PaymentServiceReference.PaymentModel[]> ViewAllPaymentAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPaymentServiceChannel : ExpenseManagementClient.PaymentServiceReference.IPaymentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaymentServiceClient : System.ServiceModel.ClientBase<ExpenseManagementClient.PaymentServiceReference.IPaymentService>, ExpenseManagementClient.PaymentServiceReference.IPaymentService {
        
        public PaymentServiceClient() {
        }
        
        public PaymentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaymentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ExpenseManagementClient.PaymentServiceReference.PaymentModel AddPayment(ExpenseManagementClient.PaymentServiceReference.PaymentModel payment) {
            return base.Channel.AddPayment(payment);
        }
        
        public System.Threading.Tasks.Task<ExpenseManagementClient.PaymentServiceReference.PaymentModel> AddPaymentAsync(ExpenseManagementClient.PaymentServiceReference.PaymentModel payment) {
            return base.Channel.AddPaymentAsync(payment);
        }
        
        public bool DeletePayment(int paymentId) {
            return base.Channel.DeletePayment(paymentId);
        }
        
        public System.Threading.Tasks.Task<bool> DeletePaymentAsync(int paymentId) {
            return base.Channel.DeletePaymentAsync(paymentId);
        }
        
        public ExpenseManagementClient.PaymentServiceReference.PaymentModel UpdatePayment(ExpenseManagementClient.PaymentServiceReference.PaymentModel payment) {
            return base.Channel.UpdatePayment(payment);
        }
        
        public System.Threading.Tasks.Task<ExpenseManagementClient.PaymentServiceReference.PaymentModel> UpdatePaymentAsync(ExpenseManagementClient.PaymentServiceReference.PaymentModel payment) {
            return base.Channel.UpdatePaymentAsync(payment);
        }
        
        public ExpenseManagementClient.PaymentServiceReference.PaymentModel ViewSinglePayment(int paymentId) {
            return base.Channel.ViewSinglePayment(paymentId);
        }
        
        public System.Threading.Tasks.Task<ExpenseManagementClient.PaymentServiceReference.PaymentModel> ViewSinglePaymentAsync(int paymentId) {
            return base.Channel.ViewSinglePaymentAsync(paymentId);
        }
        
        public ExpenseManagementClient.PaymentServiceReference.PaymentModel[] ViewAllPayment() {
            return base.Channel.ViewAllPayment();
        }
        
        public System.Threading.Tasks.Task<ExpenseManagementClient.PaymentServiceReference.PaymentModel[]> ViewAllPaymentAsync() {
            return base.Channel.ViewAllPaymentAsync();
        }
    }
}
